apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mail
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
spec:
  selector:
    app: mail
  ports:
  - protocol: "TCP"
    port: 25

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mail
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail 
  template:
    metadata:
      labels:
        app: mail 
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: smtp
        env:
        - name: RELAY_HOST
          value: {{ .Values.mail.relayHost }}
        - name: RELAY_PORT
          value: {{ .Values.mail.relayPrt }}
        - name: RELAY_USERNAME
          value: {{ .Values.mail.relayUsername }}
        - name: RELAY_PASSWORD
          value: {{ .Values.mail.relayPassword }}
        image: bytemark/smtp 
        ports:
        - containerPort: 25

